"""Taxonomy loading and dataset config generation.

A taxonomy is deliberately simple: a list of semantic classes, prompts useful
for zero-shot teacher models, Godot node candidates and rule hints.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from pydantic import BaseModel, Field


def _tiny_yaml_load(text: str) -> dict[str, Any]:
    """Load a small subset of YAML used by our configs without requiring PyYAML.

    If PyYAML is installed, we use it. Otherwise, this parser handles the simple
    mapping/list format shipped with GVI. This keeps smoke tests dependency-light.
    """
    try:
        import yaml  # type: ignore

        data = yaml.safe_load(text)
        return data or {}
    except Exception:
        pass
    # Minimal fallback: prefer JSON if config was generated that way.
    try:
        return json.loads(text)
    except Exception:
        pass
    result: dict[str, Any] = {"classes": []}
    current: dict[str, Any] | None = None
    for raw in text.splitlines():
        line = raw.rstrip()
        if not line or line.lstrip().startswith("#"):
            continue
        if line.startswith("name:"):
            result["name"] = line.split(":", 1)[1].strip().strip('"')
        elif line.startswith("version:"):
            result["version"] = line.split(":", 1)[1].strip().strip('"')
        elif line.startswith("- name:") or line.strip().startswith("- name:"):
            current = {"name": line.split(":", 1)[1].strip().strip('"')}
            result.setdefault("classes", []).append(current)
        elif current is not None and ":" in line:
            key, value = line.strip().split(":", 1)
            value = value.strip()
            if value.startswith("[") and value.endswith("]"):
                current[key] = [v.strip().strip("'\"") for v in value[1:-1].split(",") if v.strip()]
            else:
                current[key] = value.strip('"')
    return result


class TaxonomyClass(BaseModel):
    id: int
    name: str
    description: str = ""
    prompts: list[str] = Field(default_factory=list)
    godot_candidates: list[str] = Field(default_factory=list)
    color: str | None = None
    rules: dict[str, Any] = Field(default_factory=dict)


class Taxonomy(BaseModel):
    name: str = "platformer"
    version: str = "1.0"
    classes: list[TaxonomyClass] = Field(default_factory=list)
    metadata: dict[str, Any] = Field(default_factory=dict)

    @property
    def class_to_id(self) -> dict[str, int]:
        return {c.name: c.id for c in self.classes}

    @property
    def id_to_class(self) -> dict[int, str]:
        return {c.id: c.name for c in self.classes}

    @property
    def names_for_yolo(self) -> dict[int, str]:
        return {c.id: c.name for c in self.classes}

    def prompt_list(self, selected: list[str] | None = None) -> list[str]:
        allowed = set(selected) if selected else None
        prompts: list[str] = []
        for cls in self.classes:
            if allowed and cls.name not in allowed:
                continue
            prompts.extend(cls.prompts or [cls.name])
        return sorted(set(prompts))

    @classmethod
    def load(cls, path_or_name: Path | str | None = None) -> "Taxonomy":
        if path_or_name is None:
            path_or_name = "platformer"
        path = Path(path_or_name)
        if not path.exists():
            builtin = Path(__file__).resolve().parent / "configs" / f"{path_or_name}_classes.yaml"
            if builtin.exists():
                path = builtin
            else:
                root_cfg = Path.cwd() / "configs" / "training" / f"{path_or_name}_classes.yaml"
                path = root_cfg
        if not path.exists():
            raise FileNotFoundError(f"Taxonomy not found: {path_or_name}")
        data = _tiny_yaml_load(path.read_text(encoding="utf-8"))
        # Add ids if omitted.
        classes = []
        for idx, item in enumerate(data.get("classes", [])):
            item = dict(item)
            item.setdefault("id", idx)
            classes.append(item)
        data["classes"] = classes
        return cls.model_validate(data)

    def write_yolo_data_yaml(self, dataset_root: Path, path: Path | None = None) -> Path:
        path = path or dataset_root / "data.yaml"
        names_lines = "\n".join([f"  {c.id}: {c.name}" for c in self.classes])
        text = f"""# Auto-generated by GVI. Edit classes in taxonomy, not here.
path: {dataset_root.as_posix()}
train: images/train
val: images/val
test: images/test

names:
{names_lines}
"""
        path.write_text(text, encoding="utf-8")
        return path

    def write_json(self, path: Path) -> Path:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(self.model_dump_json(indent=2), encoding="utf-8")
        return path


class DatasetConfig(BaseModel):
    dataset_root: Path
    taxonomy_name: str = "platformer"
    image_extensions: list[str] = Field(default_factory=lambda: [".png", ".jpg", ".jpeg", ".webp", ".bmp"])
    train_ratio: float = 0.8
    val_ratio: float = 0.15
    test_ratio: float = 0.05
    seed: int = 42
    task: str = "segment"
    metadata: dict[str, Any] = Field(default_factory=dict)
